### ISSUE TITLE
Any screenshots for your readme?

### ISSUE THREAD

**Issue by PySimpleGUI** [TimMolga/DefilerDB#1]
Hi there!

I see you've got a GUI in your project... well, I see there's code.... do you have a screenshot you can drop in your readme?  We all like pictures :-)  Well, I do anyway.  So few Python projects have a GUI so it's always fun to see a screenshot in a readme when there is one.

**Comment by TimMolga** [comment]
I have added some GUI screens to the project!

**Comment by PySimpleGUI** [comment]
Very nice!  Dark Gray 13!  One of my favorites.
